export const SET_COUNTER = 'SET_COUNTER';
export const TODO_ITEM_FETCH_PENDING = 'TODO_ITEM_FETCH_PENDING';
export const TODO_ITEM_FETCH_SUCCESS = 'TODO_ITEM_FETCH_SUCCESS';
export const TODO_ITEM_FETCH_FAILED = 'TODO_ITEM_FETCH_FAILED';
